name: publish

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Bundle install
        run: |
          brew install grep
          bundle install

      - name: Release
        id: release
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bundle exec pod repo update
          bundle exec fastlane fastlane run pod_push use_bundle_exec:"true" path:"TCSSSLPinningPublic.podspec.json" allow_warnings:"true" skip_tests:"true" synchronous:"true"
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}